name: Terraform

on:
  push:
    branches:
      - '*'

jobs:
  terraform:
    env: 
    TF_TOKEN_app_terraform_io: PwstE3ne6VYtow.atlasv1.Kizb6rU6TjWbzTnB3GN01RCx4YUQWy1CKHKVXIyOpA7ynrsLCPzPSkQriGCfM7x80cE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Terraform Init
      run: terraform init
      working-directory: ./simple

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./simple

    - name: Terraform Apply
      if: "github.event_name == 'push' && github.ref == 'refs/heads/main'"
      run: terraform apply -auto-approve
      working-directory: ./simple
