name: Terraform

on:
  push:
    branches:
      - '*'

jobs:
  terraform:
    env:
      TF_CLI_CONFIG_FILE: /tmp/terraform.rc
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.4

    - name: Create CLI Config
      run: echo "credentials \"app.terraform.io\" { token = \"$TF_TOKEN_app_terraform_io\" }" > $TF_CLI_CONFIG_FILE

    - name: Terraform Init
      run: terraform init
      working-directory: ./simple

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./simple

    - name: Terraform Apply
      if: "github.event_name == 'push' && github.ref == 'refs/heads/main'"
      run: terraform apply -auto-approve
      working-directory: ./simple
